#pragma once

#define LV_LVGL_H_INCLUDE_SIMPLE

#define CUSTOM_SYMBOL_HEADPHONES "\xEF\x80\xA5"
#define CUSTOM_SYMBOL_DROPLET "\xEF\x81\x83"
#define CUSTOM_SYMBOL_PERCENT "\x25"
#define CUSTOM_SYMBOL_USERS_LINE "\xEE\x96\x92"
#define CUSTOM_SYMBOL_ARROWS_LEFT_RIGHT_TO_LINE "\xEE\x92\xBA"
#define CUSTOM_SYMBOL_UP_DOWN "\xEF\x8C\xB8"
#define CUSTOM_SYMBOL_WAVE_SQUARE "\xEF\xA0\xBE"
#define CUSTOM_SYMBOL_ARROW_DOWN_WIDE_SHORT "\xEF\x85\xA0"
#define CUSTOM_SYMBOL_ARROW_RIGHT_FROM_BRACKET "\xEF\x82\x8B"
#define CUSTOM_SYMBOL_CHART_SIMPLE "\xEE\x91\xB3"
#define CUSTOM_SYMBOL_CODE "\xEF\x84\xA1"
#define CUSTOM_SYMBOL_LAYER_GROUP "\xEF\x97\xBD"
#define CUSTOM_SYMBOL_RULER_HORIZONTAL "\xEF\x95\x87"
#define CUSTOM_SYMBOL_VOLUME_XMARK "\xEF\x9A\xA9"


