#pragma once

#define LV_LVGL_H_INCLUDE_SIMPLE

#define CUSTOM_SYMBOL_HEADPHONES "\xEF\x80\xA5"
#define CUSTOM_SYMBOL_DROPLET "\xEF\x81\x83"
#define CUSTOM_SYMBOL_PERCENT "\x25"
#define CUSTOM_SYMBOL_USERS_LINE "\xEE\x96\x92"
#define CUSTOM_SYMBOL_ARROWS_LEFT_RIGHT_TO_LINE "\xEE\x92\xBA"
#define CUSTOM_SYMBOL_UP_DOWN "\xEF\x8C\xB8"
#define CUSTOM_SYMBOL_WAVE_SQUARE "\xEF\xA0\xBE"
#define CUSTOM_SYMBOL_ARROW_DOWN_WIDE_SHORT "\xEF\x85\xA0"

